const express = require('express');
const router = express.Router();
const { doctorController } = require('../controllers');
const { protect } = require('../middleware/auth');
const { authorize } = require('../middleware/role');
const { ROLES } = require('../config/constants');

router.use(protect);
router.use(authorize(ROLES.DOCTOR));

router.get('/profile', doctorController.getProfile);
router.put('/profile', doctorController.updateProfile);
router.get('/patients', doctorController.getPatients);
router.get('/patients/search', doctorController.searchPatients);
router.get('/patients/:id', doctorController.getPatientDetails);
router.get('/appointments', doctorController.getAppointments);
router.get('/appointments/search', doctorController.searchAppointments);
router.put('/appointments/:id', doctorController.updateAppointment);
router.put('/appointments/:id/priority', doctorController.setPriorityAppointment);
router.post('/appointments/bulk-action', doctorController.bulkUpdateAppointments);
router.post('/upcoming-appointments', doctorController.getUpcomingAppointmentsDetails);
router.post('/meeting-link', doctorController.createMeetingLink);
router.post('/prescription', doctorController.writePrescription);
router.get('/prescriptions', doctorController.getPrescriptions);
router.get('/chats', doctorController.getChats);
router.get('/chats/:chatId/messages', doctorController.getMessages);
router.post('/blogs', doctorController.createBlog);
router.put('/blogs/:id', doctorController.updateBlog);
router.delete('/blogs/:id', doctorController.deleteBlog);
router.get('/blogs', doctorController.getMyBlogs);
router.get('/feedbacks', doctorController.getFeedbacks);
router.get('/feedbacks/search', doctorController.searchFeedbacks);
router.put('/feedbacks/:id/reply', doctorController.replyFeedback);
router.delete('/feedbacks/:id', doctorController.deleteFeedback);
router.post('/medicines', doctorController.addMedicine);
router.get('/availability', doctorController.getAvailability);
router.get('/notifications', doctorController.getNotifications);
router.get('/notifications/search', doctorController.searchNotifications);
router.put('/notifications/:id/read', doctorController.markNotificationRead);
router.put('/notifications/mark-all-read', doctorController.markAllNotificationsRead);
router.delete('/notifications/:id', doctorController.deleteNotification);
router.get('/dashboard/stats', doctorController.getDashboardStats);
router.post('/appointment/:id/complete', doctorController.completeAppointment);
router.post('/appointment/:id/reschedule', doctorController.rescheduleAppointment);

module.exports = router;
